# Generated by Django 4.2.6 on 2024-09-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.alumni')),
            ],
        ),
    ]
