# Generated by Django 4.2.6 on 2024-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='exp',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='year',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
