# Generated by Django 4.2.6 on 2024-09-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alumni_exp_alumni_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='exp',
        ),
    ]
