# Generated by Django 4.2.6 on 2024-09-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_remove_alumni_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='year',
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('projectdetails', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.experience')),
            ],
        ),
    ]
