# Generated by Django 4.2.6 on 2024-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_alumni_year_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('mentor_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
