# Generated by Django 5.0.3 on 2024-09-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_remove_alumni_passyear_alumni_endyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='user',
            new_name='alum',
        ),
    ]
