# Generated by Django 5.0.3 on 2024-09-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_rename_user_alumni_alum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='alum',
            new_name='user',
        ),
    ]
